"""The Analyst — an autonomous briefing engine, not a chatbot.

One call runs the whole desk and writes the morning note a junior analyst
would hand you: market state, your book, today's setups, what to watch,
the news that touches YOUR names, and a weekly self-audit of the system's
own live edge. Every sentence is generated by rules over computed numbers —
nothing is ever 'imagined'.
"""
from __future__ import annotations

from datetime import datetime, timezone

import numpy as np
import pandas as pd
import streamlit as st
import yfinance as yf

from .advanced import regime_quadrant
from .playbook import build_playbook
from .risk import correlation_heat, portfolio_var
from .scanner import scan_setups
from .validation import bootstrap_cagr


# ---------------------------------------------------------------------------
# News (per-ticker, shape-defensive across yfinance versions)
# ---------------------------------------------------------------------------

@st.cache_data(ttl=1800, show_spinner=False)
def ticker_news(tickers: tuple[str, ...], per_ticker: int = 3) -> pd.DataFrame:
    rows = []
    for t in tickers[:8]:                       # politeness cap
        try:
            items = yf.Ticker(t).news or []
        except Exception:
            continue
        for it in items[:per_ticker]:
            try:
                content = it.get("content", it)
                title = content.get("title") or it.get("title")
                if not title:
                    continue
                url = (content.get("canonicalUrl", {}) or {}).get("url") \
                    or it.get("link", "")
                pub = (content.get("provider", {}) or {}).get("displayName") \
                    or it.get("publisher", "")
                when = content.get("pubDate") or ""
                rows.append({"ticker": t, "headline": title,
                             "source": pub, "when": str(when)[:16],
                             "url": url})
            except Exception:
                continue
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Self-audit — the system grades ITSELF on the live track record
# ---------------------------------------------------------------------------

def self_audit(blotter: pd.DataFrame, account: float) -> list[str]:
    notes = []
    closed = blotter[blotter["status"] == "CLOSED"] if len(blotter) else \
        pd.DataFrame()
    if len(closed) < 8:
        notes.append(f"📋 Track record: {len(closed)} closed trades — "
                     f"need ≥8 before the statistics mean anything. "
                     f"Keep recording every plan.")
        return notes
    hit = float((closed["P&L $"] > 0).mean() * 100)
    exp = float(closed["P&L $"].mean())
    notes.append(f"📋 Live record: {len(closed)} closed · hit rate "
                 f"{hit:.0f}% · expectancy ${exp:+,.0f}/trade.")
    bs = bootstrap_cagr(closed["P&L $"], starting=account)
    if "error" not in bs:
        notes.append(f"🔬 Bootstrap 90% CI on your LIVE trades: "
                     f"{bs['CI90_low_%']}% … {bs['CI90_high_%']}% — "
                     f"{bs['verdict']}")
        if not bs["excludes_zero"]:
            notes.append("⚠️ The live edge is NOT yet statistically proven "
                         "— trade the minimum size until the CI clears zero.")
    return notes


# ---------------------------------------------------------------------------
# The briefing
# ---------------------------------------------------------------------------

def morning_briefing(spy: pd.DataFrame,
                     universe_data: dict[str, pd.DataFrame],
                     blotter: pd.DataFrame | None,
                     account: float,
                     risk_pct: float,
                     event_gauge: dict | None = None) -> dict:
    """Run the desk, return a structured briefing with plain-language notes."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    brief = {"stamp": now, "market": [], "book": [], "setups": [],
             "watch": [], "audit": [], "setups_table": pd.DataFrame(),
             "news_tickers": []}

    # ---- 1. Market ---------------------------------------------------------
    reg = regime_quadrant(spy)
    brief["regime"] = reg
    brief["market"].append(f"Market regime: **{reg['regime']}** — "
                           f"{reg['playbook']}")
    if event_gauge:
        brief["market"].append(f"Macro event gauge: **{event_gauge['label']}**"
                               f" (score {event_gauge['score']:+.2f}).")

    # ---- 2. Your book -------------------------------------------------------
    open_pos = (blotter[blotter["status"] == "OPEN"]
                if blotter is not None and len(blotter) else pd.DataFrame())
    if len(open_pos):
        poss, rets_map = [], {}
        for _, r in open_pos.iterrows():
            t = r["ticker"]
            df_t = universe_data.get(t)
            if df_t is None or len(df_t) < 220:
                continue
            pb = build_playbook(df_t, account=account, risk_pct=risk_pct,
                                in_position=True, entry=float(r["entry"]),
                                stop=float(r["stop"]))
            brief["book"].append(f"**{t}** ({int(r['shares'])} sh, "
                                 f"{r['P&L %']:+.1f}%): {pb['urgency']} — "
                                 f"{pb['instruction']}")
            poss.append({"ticker": t, "shares": int(r["shares"]),
                         "entry": float(r["entry"]), "stop": float(r["stop"])})
            rets_map[t] = df_t["Close"].pct_change().dropna()
        pv = portfolio_var(poss, rets_map, account) if poss else {}
        ch = correlation_heat(poss, rets_map, account) if len(poss) > 1 else {}
        if pv:
            brief["book"].append(f"Book risk: 1-day VaR ${pv['VaR_$']:,.0f} "
                                 f"({pv['VaR_%']}%) · gross exposure "
                                 f"{pv['gross_exposure_%']}%.")
        if ch and ch.get("warning"):
            brief["book"].append(f"⚠️ Correlation alert: avg pairwise "
                                 f"{ch['avg_correlation']} — your positions "
                                 f"are effectively one trade.")
    else:
        brief["book"].append("No open positions — full dry powder.")

    # ---- 3. Today's setups ---------------------------------------------------
    setups = scan_setups(universe_data, account=account, risk_pct=risk_pct)
    brief["setups_table"] = setups
    if len(setups):
        enters = setups[setups["urgency"] == "🟢 ENTER"]
        fast = setups[setups["urgency"] == "🟡 FAST"]
        if len(enters):
            top = enters.iloc[0]
            brief["setups"].append(f"**{len(enters)} full entries** today — "
                                   f"strongest: **{top['ticker']}** "
                                   f"(score {top['score']}, BX {top['BX']}): "
                                   f"{top['shares']} sh ≈ ${top['price']:,.2f}"
                                   f", stop ${top['stop']:,.2f}.")
        if len(fast):
            brief["setups"].append(f"**{len(fast)} dip scalp(s)**: "
                                   + ", ".join(fast["ticker"].tolist()) +
                                   " — RSI2 panic inside uptrends; quick "
                                   "in/out on the snap-back.")
        stalk = setups[setups["urgency"] == "👀 STALK"]
        for _, s_ in stalk.head(3).iterrows():
            brief["watch"].append(f"**{s_['ticker']}** is one gate away "
                                  f"({s_['gates']}) with score {s_['score']}"
                                  f" — set an alert near ${s_['price']:,.2f}.")
    else:
        brief["setups"].append("Zero setups pass the gates today. The "
                               "correct trade is patience.")

    # news targets: holdings + top setups
    news_t = list(open_pos["ticker"]) if len(open_pos) else []
    if len(setups):
        news_t += setups["ticker"].head(5).tolist()
    brief["news_tickers"] = tuple(dict.fromkeys(news_t))[:8]

    # ---- 4. Self-audit ---------------------------------------------------------
    if blotter is not None and len(blotter):
        brief["audit"] = self_audit(blotter, account)
    return brief
